baseURL = "https://example.com/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.109.0"
    max = ""
  [[module.imports]]
    path = "github.com/juggernautjp/hugo-widebs5-dependencies"
#  [[module.imports]]
#    path = "github.com/FortAwesome/Font-Awesome"


