module:
  module.hugoVersion:
    extended: true
    min: "0.109.0"
    max: ""

  imports:
    - path: "github.com/juggernautjp/hugo-widebs5-dependencies"
      mounts:
        - source: "assets/scss"
          target: "assets/docs/scss"
        - source: "assets/js"
          target: "assets/docs/js"
