module:
  module.hugoVersion:
    extended: true
    min: "0.109.0"
    max: ""
#  mounts:
#    - source: "assets/scss"
#      target: "assets/docs/scss"
#    - source: "assets/js"
#      target: "assets/docs/js"
#    - source: "assets"
#      target: "assets"
  imports:
    - path: "github.com/juggernautjp/hugo-widebs5-dependencies"

params:
  options:
    bsa_path: "assets/bootstrap"
