module:
  module.hugoVersion:
    extended: true
    min: "0.109.0"
    max: ""
  mounts:
    - source: ".browserslistrc"
      target: "content/.browserslistrc"
    - source: "content"
      target: "content"
#    - source: "assets/scss"
#      target: "assets/docs/scss"
#    - source: "assets/js"
#      target: "assets/docs/js"
#    - source: "assets"
#      target: "assets"
  imports:
    - path: "github.com/juggernautjp/hugo-widebs5-dependencies"
