[module]
# _merge = "deep"
[module.hugoVersion]
  extended = true
# workaround for https://github.com/golang/go/issues/37397
# Workaround for https://github.com/gohugoio/hugo/issues/6945
[[module.mounts]]
  source = "assets/bootstrap/scss/_vendor"
  target = "assets/bootstrap/scss/vendor"
# mount asserts directory
[[module.mounts]]
  source = "assets"
  target = "assets"
# [[module.mounts]]
#   source = "layouts"
#   target = "layouts"
# mount static directory
# [[module.mounts]]
#   source = "static"
#   target = "static"
# Dependencies are brought in as modules
# and mount points are declared
[[module.imports]]
  path = "github.com/twbs/bootstrap"
  disable = false
[[module.imports.mounts]]
  source = "scss"
  target = "assets/bootstrap/scss"
[[module.imports.mounts]]
  source = "js"
  target = "assets/bootstrap/js"
